"""
artifacts.py - Repo-owned artifacts generated by AAAS.
"""

from datetime import datetime
from pathlib import Path


LEGION_FILE = "legion.md"
PRIMER_FILE = "primer.md"


def build_legion_prompt(
    project_text: str,
    project_summary: str,
    recommended_packs: list[str],
) -> str:
    today = datetime.now().strftime("%Y-%m-%d")
    packs_text = (
        ", ".join(recommended_packs) if recommended_packs else "none detected yet"
    )
    return f"""You are Legion, an expert software onboarding and execution agent.

Write a repo intelligence file called legion.md for the scanned project.

Requirements:
- Be specific to the provided repository context.
- Do not invent files, commands, tests, or systems not present in the context.
- Keep the tone operational and useful for future coding agents.
- Prefer concise bullets and short sections.

The file must have these exact sections:

# Legion
_Last updated: {today}_

## What this repo is
(2-4 sentences)

## Repo summary
(include: {project_summary})

## Architecture map
(bullets)

## Key files and directories
(table: Path | Purpose)

## Commands
(bullets for setup, run, build, validate)

## Detected stack
(bullets)

## Recommended packs
(bullets, starting from: {packs_text})

## Working agreements
(bullets for code style, safety, and boundaries)

## Known gaps
(bullets)

## Next best actions
(numbered list)

Project files:
{project_text}

Write legion.md now."""


def write_legion(root: str | Path, content: str) -> Path:
    path = Path(root) / LEGION_FILE
    path.write_text(content, encoding="utf-8")
    return path


def update_primer(
    root: str | Path,
    project_summary: str,
    recommended_packs: list[str],
    generated_paths: list[str],
) -> Path:
    root_path = Path(root)
    path = root_path / PRIMER_FILE
    today = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    packs_text = ", ".join(recommended_packs) if recommended_packs else "none"
    generated_text = ", ".join(generated_paths) if generated_paths else "none"

    entry = (
        f"## Run {today}\n"
        f"- Summary: {project_summary}\n"
        f"- Recommended packs: {packs_text}\n"
        f"- Generated or refreshed: {generated_text}\n"
        "- Notes: AAAS scanned the repo and updated operational memory for the next run.\n"
        "- Next step: Review legion.md, then continue work with chat.py or a workflow doc.\n\n"
    )

    if path.exists():
        existing = path.read_text(encoding="utf-8")
    else:
        existing = "# Primer\n\nOperational memory for this repo. Newest runs appear first.\n\n"

    if existing.startswith("# Primer\n"):
        header, _, body = existing.partition("\n\n")
        updated = f"{header}\n\n{entry}{body}"
    else:
        updated = f"# Primer\n\n{entry}{existing}"

    path.write_text(updated, encoding="utf-8")
    return path
